### ISSUE TITLE
Issue with type Double/Int

### ISSUE THREAD

**Issue by DKalachniuk** [alickbass/SwiftyJSONModel#12]
if I do 
```swift
try? JSON(0.0).value() as Int
```
this equals to `nil` as well as the opposite:

```swift
try? JSON(-5).value() as Double
``` 
is also `nil`

**Comment by alickbass** [comment]
Thanks for submitting the issue! This is definitely a bug that was caused by the fact that `value()` method uses the method that returns `Any`. I will resolve this issue in short notice.

**Comment by DKalachniuk** [comment]
Thank you
currently as a workaround, I'm using 

`?? 0.0`

`cost =  object.value(for: .cost,.r180) ?? 0.0`

**Comment by alickbass** [comment]
Indeed, this can be a temp fix, but it won't give you an error if, for example, you will receive `String` instead of a `Number`
