### ISSUE TITLE
How can I access to some values with are nested on a JSON ..

### ISSUE THREAD

**Issue by syllerim** [alickbass/SwiftyJSONModel#9]
How can I have a struct with a structure which is not correspondent with the JSON hierarchy?
Lets suppose I have the next JSON
``` json
{
  "id": 5128581,
  "name": "New York",
  "cod": 200
  "main": {
    "temp": 263.76,
    "pressure": 1038,
    "humidity": 92,
    "temp_min": 259.15,
    "temp_max": 269.15
  }
}
```
And I want to have a struct with the values for the keys name and `main->temp`.
How can I do it?

**Comment by alickbass** [comment]
For now you have to create 2 models separately. One for `root` model and the other one is for `main` object. However, I think that it would be nice to have possibility to do it within `root` model. This is nice to have feature and I'll implement it next version

**Comment by alickbass** [comment]
I added possibility to access nested `json`. In your case it would look like this:

```swift
struct MyModel: JSONObjectInitializable {
    enum PropertyKey: String {
        case main, temp
    }
    
    let temp: Double
    
    init(object: JSONObject<PropertyKey>) throws {
        temp = try object.value(for: .main, .temp)
    }
}
```
